lightning_data_module:
  _target_: src.multimodal_llm.data.scicap.SciCapDataModule
  root_dir: data/
  batch_size: 32
  num_workers: 0

lightning_module:
  _target_: src.multimodal_llm.pl_modules.pl_module.BasicLightningModule
  optimizer_cls: torch.optim.AdamW
  model: null
  loss_fn: 
    _target_: torch.nn.CrossEntropyLoss
  

trainer:
  _target_: pytorch_lightning.Trainer
  max_epochs: 1

tasks:
  - fit
